### ISSUE TITLE
potential wrong version number

### ISSUE THREAD

**Issue by the3dfox** [SidorkinAlex/Opportunities_kanban#10]
according to the github page the version of the module should be 2.0

in the manifest.php the version of the module is defined with 1.0.3 instead

**Comment by SidorkinAlex** [comment]
Thank you I will fix it in the next patch

**Comment by SidorkinAlex** [comment]
I fixed this bugs in release 2.0.1
https://github.com/SidorkinAlex/Opportunities_kanban/releases/download/2.0.1/Build_2_0_1.zip
