### ISSUE TITLE
nothing gets displayed in the kanban boards

### ISSUE THREAD

**Issue by the3dfox** [SidorkinAlex/Opportunities_kanban#11]
managed to install the module.
System:
SuiteCRM 7.11.22
PHP 7.4
MySQL 5.7

after the install I did a quick rebuild and activated the kanban for "opportunities" inside the Kanban Board Settings in the admin panel. After that I made the settings within the opportunities module

![kanban-settings](https://user-images.githubusercontent.com/84663901/138456704-d4e6e0d8-a533-444e-a070-7ca868282d42.png)

unfortunately the kanban board doesn't show any entries. 

![kanban-board](https://user-images.githubusercontent.com/84663901/138456014-8a5abcb3-4810-40c5-9385-ad79eed2eb4e.png)

Currently I have two entries in my system in different stages 1. "Qualification" 2. "Prospecting"

![opportunities](https://user-images.githubusercontent.com/84663901/138456400-9c2b13dd-df4c-4139-8222-a6c7de476d40.png)

any advice is highly appreciated

**Comment by SidorkinAlex** [comment]
Please go to the whiteboard page.
Open the developer tools (ctrl +shift + i).
Open the Network tab.
In the filter, select Fetch/XHR.
Reload the page.
What is the status of the index.php request?module=BOARD&recipient_module=Opportunities&action=getData&to_pdf=true ?
please take a screenshot of the response to this request.
![image](https://user-images.githubusercontent.com/16462838/138551247-e73f4fb3-964b-4d32-b70c-c729dd3964a1.png)
![image](https://user-images.githubusercontent.com/16462838/138551256-be9af21a-207e-4111-9f94-e537ca6bef51.png)

**Comment by the3dfox** [comment]
Hi, did what you asked for:

![kanban_view_preview](https://user-images.githubusercontent.com/84663901/138660138-ceba854a-ab7f-45c5-813f-aec3d0f27cec.png)

![kanban_view_response](https://user-images.githubusercontent.com/84663901/138660613-55d966e3-3622-4ca8-9de7-5977954bba47.png)

`<br />
<b>Warning</b>:  Use of undefined constant nul - assumed 'nul' (this will throw an Error in a future version of PHP) in <b>.../suiteCRM/TestSuite-7/modules/BOARD/controller.php</b> on line <b>15</b><br />
{"Qualification":[{"id":"2d546763-f23e-bbd6-2ec3-6172b0b73c71","beanCardName":" Test Opp 2","stage":"Qualification"}],"Prospecting":[{"id":"5f2f00ba-fc49-58c4-adc1-6172ae839fba","beanCardName":" Test Opportunity","stage":"Prospecting"}]}`


thank you, hope this means something to you

**Comment by SidorkinAlex** [comment]
you should disable php error output.

Output them to the log file, this will help solve the problem

**Comment by SidorkinAlex** [comment]
I fixed this bugs in  release 2.0.1 
https://github.com/SidorkinAlex/Opportunities_kanban/releases/download/2.0.1/Build_2_0_1.zip

**Comment by the3dfox** [comment]
awesome man, it works like a charm. So happy and thank you for your assistance.
