### ISSUE TITLE
not compatible with php 7.3

### ISSUE THREAD

**Issue by the3dfox** [SidorkinAlex/Opportunities_kanban#12]
although I managed to get the plugin installed with php version 7.4 I cannot fully install the plugin with php 7.3

The error during installation is:
also installation stops at 82%

![kanban-board-7 3-install](https://user-images.githubusercontent.com/84663901/138850106-6b2fd8b4-88c1-419b-8cd2-a528757d8514.png)

`Parse error: syntax error, unexpected 'SugarBean' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in ../TestSuite-7/modules/BOARD/BOARD.php on line 68`

is the module designed to only run on php 7.4 if so it would be nice to add this to the plugin description otherwise I consider this as an issue.

If you need any more information let me know

**Comment by SidorkinAlex** [comment]
this error appears due to the php version
unfortunately php 7.3 does not support object property typing, and this problem can be solved by removing object property typing in the code. But this is a bad practice.
I will specify the minimum php 7.4 version for this package to work.
