### ISSUE TITLE
SuiteCRM Version 8.0.0 compatibility

### ISSUE THREAD

**Issue by Jonyx4** [SidorkinAlex/Opportunities_kanban#13]
Is this module already compatible with SuiteCRM Version 8.0.0 ?

Thank you!

**Comment by SidorkinAlex** [comment]
Hi, there is a kanban item for modules in the description of the SuiteCRM 8 Rodmap, and there will be no sense in this package, so at the moment there are no plans to transfer it to SuiteCRM 8. https://suitecrm.com/suitecrm-roadmap/

**Comment by Jonyx4** [comment]
Hello there. I updated to 8.0.. 8.1 and Kanban is not present. I read again the suitecrm roadmap and there is no more kanban there!

Any chance to revive this project and make it compatible with SuiteCRM 8+?

Regards!
