### ISSUE TITLE
 SuiteCRM Version 8.x.x compatibility Ref. #13 

### ISSUE THREAD

**Issue by Jonyx4** [SidorkinAlex/Opportunities_kanban#14]
Hello there. I updated to 8.0.. 8.1 and Kanban is not present. I read again the suitecrm roadmap and there is no more kanban there!

Any chance to revive this project and make it compatible with SuiteCRM 8+?

Regards!

**Comment by SidorkinAlex** [comment]
Hi, I am currently actively engaged in a project in my spare time to create a fork from suiteCRM7.12. In my opinion, the project has turned around a lot, making strong internal architectural changes and switching to the SPA concept and limitations of frontend customization capabilities (choosing a framework and not the most popular). Therefore, I am not planning to adapt the packages I wrote earlier to SuiteCRM 8. I plan to gather a Community around a new fork project from SuiteCRM BearCRM(https://github.com/Bear-CRM-ERP/Bear-CRM-ERP-core ). Now the basic concepts and core of the team are being formed.
