### ISSUE TITLE
Проект закрыт?

### ISSUE THREAD

**Issue by IgorA100** [SidorkinAlex/Opportunities_kanban#15]
Долгое время не было изменений :(

**Comment by SidorkinAlex** [comment]
Какие изменения хотелось бы ? насколько я понимаю ошибок или открытых тикетов на баги нет, соответственно нет изменений в коде. Если есть идеи куда двигать проект открыта возможность сделать МР с улучшением или сделать форк и двигать дальше самостоятельно. Переписывать под 8 сьют это и ради этого изучать ангуляр желания нет. Поэтому скорее всего да проект закрыт, поскольку делать под легаси версию  SuiteCRM не хочется.
