### ISSUE TITLE
Doesn't Install SuiteCRM v7.11.20

### ISSUE THREAD

**Issue by WebSpectrum** [SidorkinAlex/Opportunities_kanban#8]
Doesn't seem to install on SuiteCRM 7.11.20

**Comment by WebSpectrum** [comment]
PHP 7.3 - error log:

[02-Aug-2021 01:40:31 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function post_install() in /home/username/suite.domain.com/modules/Administration/UpgradeWizard_commit.php:349
Stack trace:
#0 /home/username/suite.domain.com/include/MVC/View/SugarView.php(839): include_once()
#1 /home/username/suite.domain.com/include/MVC/View/views/view.classic.php(72): SugarView->includeClassicFile('cache/upgrades/...')
#2 /home/username/suite.domain.com/include/MVC/View/SugarView.php(226): ViewClassic->display()
#3 /home/username/suite.domain.com/include/MVC/Controller/SugarController.php(444): SugarView->process()
#4 /home/username/suite.domain.com/include/MVC/Controller/SugarController.php(375): SugarController->processView()
#5 /home/username/suite.domain.com/include/MVC/SugarApplication.php(113): SugarController->execute()
#6 /home/username/suite.domain.com/index.php(52): SugarApplication->execute()
#7 {main}
  thrown in /home/username/suite.domain.com/modules/Administration/UpgradeWizard_commit.php on line 349

**Comment by SidorkinAlex** [comment]
it is not blocked Error, after installation, you can use the package.

The bug will be fixed in the next release,

**Comment by WebSpectrum** [comment]
Let me check, I had the settings but couldn't get it to work properly ... thanks

**Comment by WebSpectrum** [comment]
Here are screenshots:
https://paste.pics/DEJNJ
https://paste.pics/DEJN9

**Comment by WebSpectrum** [comment]
here are screenshots:
https://paste.pics/DEJO5
https://paste.pics/DEJO7

**Comment by WebSpectrum** [comment]
OK, thanks .... I see 'Uncaught ReferenceError: jKanban is not defined' in console, here are screenshots:

https://paste.pics/DEKJT
https://paste.pics/DEKJX

**Comment by SidorkinAlex** [comment]
I think you didn't have enough rights for the custom/include folder when installing the package
You can manually copy the /Sugar Modules/custom/ folder from the archive to the custom of your project. After that, the package should work.

**Comment by WebSpectrum** [comment]
Yes, I see now it was a permissions issue, a lot of folders need 775 recursive permissions... It is working now and thanks for taking the time to help me ....

**Comment by SidorkinAlex** [comment]
I was glad to help
